### ISSUE TITLE
This tune triggers error

### ISSUE THREAD

**Issue by mokkurkalve** [getmicah/spotify-now#10]
This tune triggers error:
https://open.spotify.com/track/18LH521rZYbQxQvaGIdtuh?si=18d2039418944cad
This is what are returned:
```
env LANG=C LC_ALL=C spmd '%artist ★ %album ★ %title'
sed: -e expression #1, char 31: unknown option to `s'
```
I have not yet come by other records that fails this.

**Comment by cowellmi** [comment]
Hey thanks for letting me know.
It was because there's a forward slash in the album title. I added a line to escape slashes.
